# Generated by Django 4.2 on 2023-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('No', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_Number', models.IntegerField()),
                ('open_time', models.CharField(max_length=100)),
                ('close_time', models.CharField(max_length=100)),
            ],
        ),
    ]
