# Generated by Django 4.2 on 2023-12-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Kelassor Airport'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Kelassor Flight'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(help_text='price is Rial'),
        ),
    ]
