# Generated by Django 4.2 on 2023-12-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': 'Kelassor Train'},
        ),
    ]
