# Generated by Django 4.2 on 2023-12-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_Name', models.CharField(max_length=250)),
                ('Origin', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=250)),
                ('Date_Of_Departure', models.DateField()),
                ('Time_Of_Departure', models.TimeField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
